# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'CollectionMenuTag' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CollectionMenuTag
  
  pod 'Masonry'
  pod 'JQCollectionViewAlignLayout'

  target 'CollectionMenuTagTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CollectionMenuTagUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
